#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum { N=256, WORDS=4, MAXC=256, CHANNELS=3, COMPS=7 };
typedef struct { uint64_t row[N][WORDS]; } Mat;
typedef struct { uint64_t bits[CHANNELS][WORDS]; } Obs;
typedef struct { uint32_t oldc,rowdeg,coldeg,diag; uint64_t out_hash,in_hash; } Sig;
typedef struct { unsigned v[3]; } Cycle3;
static const unsigned lens[COMPS]={9,10,11,12,13,14,15};
static uint64_t mix64(uint64_t x){x^=x>>30;x*=UINT64_C(0xbf58476d1ce4e5b9);x^=x>>27;x*=UINT64_C(0x94d049bb133111eb);x^=x>>31;return x;}
static unsigned bit(const Mat*m,unsigned r,unsigned c){return (unsigned)((m->row[r][c>>6]>>(c&63u))&1u);} static void tog(Mat*m,unsigned r,unsigned c){m->row[r][c>>6]^=UINT64_C(1)<<(c&63u);}
static void build(Mat*m){memset(m,0,sizeof(*m));unsigned o=0;for(unsigned g=0;g<COMPS;++g){for(unsigned j=0;j<lens[g];++j,++o){for(unsigned p=0;p<3;++p){unsigned r=3*o+p;tog(m,r,r);if(j+1<lens[g])tog(m,r,3*(o+1)+p);}}}}
static void build_obs(Obs*o){memset(o,0,sizeof(*o));unsigned orb=0;for(unsigned g=0;g<COMPS;++g){unsigned ch=g%3;for(unsigned j=0;j<lens[g];++j,++orb)for(unsigned p=0;p<3;++p){unsigned x=3*orb+p;o->bits[ch][x>>6]|=UINT64_C(1)<<(x&63u);}}}
static int cmpu(const void*a,const void*b){uint32_t x=*(const uint32_t*)a,y=*(const uint32_t*)b;return (x>y)-(x<y);} static uint64_t mh(uint32_t*a,unsigned n,uint64_t s){qsort(a,n,sizeof(uint32_t),cmpu);uint64_t h=mix64(s^n);for(unsigned i=0;i<n;++i)h=mix64(h^((uint64_t)a[i]+UINT64_C(0x9e3779b97f4a7c15)*(i+1)));return h;}
static int less(const Sig*a,const Sig*b){
#define C(f) do{if(a->f<b->f)return 1;if(a->f>b->f)return 0;}while(0)
C(oldc);C(rowdeg);C(coldeg);C(diag);C(out_hash);C(in_hash);
#undef C
return 0;} static int eq(const Sig*a,const Sig*b){return a->oldc==b->oldc&&a->rowdeg==b->rowdeg&&a->coldeg==b->coldeg&&a->diag==b->diag&&a->out_hash==b->out_hash&&a->in_hash==b->in_hash;}
static void sortidx(unsigned idx[N],const Sig s[N]){for(unsigned i=0;i<N;++i)idx[i]=i;for(unsigned i=1;i<N;++i){unsigned x=idx[i],j=i;while(j&&less(&s[x],&s[idx[j-1]])){idx[j]=idx[j-1];--j;}idx[j]=x;}}
static unsigned refine(const Mat*m,uint32_t col[N],unsigned*rounds){unsigned rd[N]={0},cd[N]={0};for(unsigned r=0;r<N;++r)for(unsigned c=0;c<N;++c)if(bit(m,r,c)){++rd[r];++cd[c];}Sig s[N];for(unsigned i=0;i<N;++i)s[i]=(Sig){0,rd[i],cd[i],bit(m,i,i),0,0};unsigned ord[N];sortidx(ord,s);uint32_t k=0;col[ord[0]]=0;for(unsigned j=1;j<N;++j){if(!eq(&s[ord[j]],&s[ord[j-1]]))++k;col[ord[j]]=k;}for(unsigned it=0;it<N;++it){for(unsigned i=0;i<N;++i){uint32_t out[N],in[N];unsigned no=0,ni=0;for(unsigned c=0;c<N;++c)if(bit(m,i,c))out[no++]=col[c];for(unsigned r=0;r<N;++r)if(bit(m,r,i))in[ni++]=col[r];s[i]=(Sig){col[i],rd[i],cd[i],bit(m,i,i),mh(out,no,17),mh(in,ni,31)};}sortidx(ord,s);uint32_t next[N],nk=0;next[ord[0]]=0;for(unsigned j=1;j<N;++j){if(!eq(&s[ord[j]],&s[ord[j-1]]))++nk;next[ord[j]]=nk;}int same=1;for(unsigned i=0;i<N;++i)if(next[i]!=col[i]){same=0;break;}memcpy(col,next,sizeof(next));*rounds=it+1;if(same)return nk+1;}return 0;}
static unsigned candidates(const uint32_t col[N],unsigned classes,Cycle3 out[MAXC],unsigned*other){unsigned cnt[N]={0};for(unsigned i=0;i<N;++i)++cnt[col[i]];unsigned n=0;*other=0;for(unsigned c=0;c<classes;++c){if(cnt[c]==3){unsigned q=0;for(unsigned i=0;i<N;++i)if(col[i]==c)out[n].v[q++]=i;++n;}else if(cnt[c]>1)++*other;}return n;}
static unsigned cyc(unsigned x,const Cycle3*c,unsigned dir){for(unsigned i=0;i<3;++i)if(x==c->v[i])return c->v[(i+dir)%3];return x;} static unsigned mapx(unsigned x,const Cycle3*c,unsigned n,const unsigned sel[MAXC],unsigned dir){for(unsigned i=0;i<n;++i)if(sel[i]){unsigned y=cyc(x,&c[i],dir);if(y!=x)return y;}return x;} static int commute(const Mat*m,const Cycle3*c,unsigned n,const unsigned sel[MAXC],unsigned dir){for(unsigned r=0;r<N;++r){unsigned pr=mapx(r,c,n,sel,dir);for(unsigned q=0;q<N;++q){unsigned pc=mapx(q,c,n,sel,dir);if(bit(m,pr,pc)!=bit(m,r,q))return 0;}}return 1;}
static void reqgraph(const Mat*m,const Cycle3*c,unsigned n,unsigned req[MAXC][MAXC]){memset(req,0,sizeof(unsigned)*MAXC*MAXC);for(unsigned i=0;i<n;++i)for(unsigned j=i+1;j<n;++j){int hit=0;for(unsigned a=0;a<3&&!hit;++a)for(unsigned b=0;b<3&&!hit;++b)if(bit(m,c[i].v[a],c[j].v[b])||bit(m,c[j].v[b],c[i].v[a]))hit=1;if(hit)req[i][j]=req[j][i]=1;}}
static unsigned comps(const unsigned req[MAXC][MAXC],unsigned n,unsigned co[MAXC]){for(unsigned i=0;i<n;++i)co[i]=MAXC;unsigned nc=0;for(unsigned s=0;s<n;++s)if(co[s]==MAXC){unsigned q[MAXC],h=0,t=0;q[t++]=s;co[s]=nc;while(h<t){unsigned u=q[h++];for(unsigned v=0;v<n;++v)if(req[u][v]&&co[v]==MAXC){co[v]=nc;q[t++]=v;}}++nc;}return nc;}
static unsigned csize(const unsigned co[MAXC],unsigned n,unsigned c){unsigned z=0;for(unsigned i=0;i<n;++i)if(co[i]==c)++z;return z;} static unsigned channel(const Obs*o,const Cycle3*c,const unsigned co[MAXC],unsigned n,unsigned cc){unsigned mask=0;for(unsigned i=0;i<n;++i)if(co[i]==cc)for(unsigned a=0;a<3;++a){unsigned x=c[i].v[a];for(unsigned ch=0;ch<CHANNELS;++ch)if((o->bits[ch][x>>6]>>(x&63u))&1u)mask|=1u<<ch;}return mask;} static unsigned pc(unsigned x){unsigned n=0;while(x){n+=x&1;x>>=1;}return n;}
int main(void){Mat M;Obs O;build(&M);build_obs(&O);uint32_t col[N];unsigned rounds=0,classes=refine(&M,col,&rounds),other=0;Cycle3 cand[MAXC];unsigned n=candidates(col,classes,cand,&other);printf("classes=%u cand=%u other=%u rounds=%u\n",classes,n,other,rounds);if(n!=84||other!=1)return 2;unsigned indiv=0;for(unsigned i=0;i<n;++i){unsigned sel[MAXC]={0};sel[i]=1;if(commute(&M,cand,n,sel,1))++indiv;}printf("indiv=%u\n",indiv);if(indiv!=0)return 3;unsigned req[MAXC][MAXC];reqgraph(&M,cand,n,req);unsigned edges=0;for(unsigned i=0;i<n;++i)for(unsigned j=i+1;j<n;++j)edges+=req[i][j];unsigned co[MAXC];unsigned nc=comps(req,n,co);printf("edges=%u comps=%u sizes",edges,nc);for(unsigned c=0;c<nc;++c)printf(" %u",csize(co,n,c));puts("");if(edges!=77||nc!=7)return 4;unsigned chan[MAXC],conf=0;for(unsigned c=0;c<nc;++c){chan[c]=channel(&O,cand,co,n,c);if(pc(chan[c])!=1)return 5;}for(unsigned a=0;a<nc;++a)for(unsigned b=a+1;b<nc;++b)if(chan[a]==chan[b])++conf;printf("conf=%u\n",conf);if(conf!=5)return 6;unsigned bestm=0,bestscore=0,bestc=0,adm=0;for(unsigned mask=0;mask<(1u<<nc);++mask){int ok=1;for(unsigned a=0;a<nc&&ok;++a)if(mask&(1u<<a))for(unsigned b=a+1;b<nc;++b)if((mask&(1u<<b))&&chan[a]==chan[b]){ok=0;break;}if(!ok)continue;unsigned sel[MAXC]={0};for(unsigned i=0;i<n;++i)if(mask&(1u<<co[i]))sel[i]=1;if(!commute(&M,cand,n,sel,1))continue;++adm;unsigned score=0,k=0;for(unsigned c=0;c<nc;++c)if(mask&(1u<<c)){score+=csize(co,n,c);++k;}if(score>bestscore){bestscore=score;bestm=mask;bestc=k;}}
printf("adm=%u bestc=%u score=%u quotient=%u\n",adm,bestc,bestscore,N-2*bestscore);if(bestscore!=42||N-2*bestscore!=172)return 7;unsigned sel[MAXC]={0};for(unsigned i=0;i<n;++i)if(bestm&(1u<<co[i]))sel[i]=1;if(!commute(&M,cand,n,sel,2))return 8;printf("ok c3_candidates=%u tail=4 selected=%u quotient=%u orientations=2\n",n,bestscore,N-2*bestscore);return 0;}
