#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
 * Bidirectional symmetry-quotient benchmark for the RSA-260 research lane.
 *
 * This is deliberately NOT the generic synthetic matrix and NOT RSA-260 data.
 * It constructs a 256-coordinate GF(2) operator with a declared order-two
 * coordinate action: swap each opposite pair (2i,2i+1), i=0..127.
 *
 * The operator is M = Q tensor I_2 where Q is the sparse 128x128 path-difference
 * matrix
 *
 *   (Qz)_i = z_i + z_{i+1},  i=0..126,
 *   (Qz)_127 = 0.
 *
 * Hence M commutes with pair-swap.  On the invariant carrier x_{2i}=x_{2i+1},
 * quotient/project and lift are exact:
 *
 *   project(lift(z)) = z
 *   M(lift(z)) = lift(Qz)
 *   lift(project(x)) = x  for invariant x.
 *
 * Q has rank 127 and one-dimensional kernel generated by the all-ones vector.
 * Its lifted invariant kernel vector is all ones in 256 coordinates and is
 * verified directly against M.
 *
 * Over GF(2), this is an orbit/equitable-partition quotient, NOT a +/- spectral
 * decomposition of the order-two action (because +1 = -1 in characteristic 2).
 */

enum { QWIDTH=128, WIDTH=256, QWORDS=2, WORDS=4 };
typedef struct { uint64_t w[QWORDS]; } Vec128;
typedef struct { uint64_t w[WORDS]; } Vec256;
typedef struct { uint64_t row[QWIDTH][QWORDS]; } Mat128;
typedef struct { uint64_t row[WIDTH][WORDS]; } Mat256;

static unsigned parity64(uint64_t x){ return (unsigned)(__builtin_popcountll((unsigned long long)x)&1u); }
static unsigned bit128(const Vec128*v,unsigned i){ return (unsigned)((v->w[i>>6]>>(i&63u))&1u); }
static unsigned bit256(const Vec256*v,unsigned i){ return (unsigned)((v->w[i>>6]>>(i&63u))&1u); }
static void set128(Vec128*v,unsigned i){ v->w[i>>6]|=UINT64_C(1)<<(i&63u); }
static void set256(Vec256*v,unsigned i){ v->w[i>>6]|=UINT64_C(1)<<(i&63u); }
static int eq128(const Vec128*a,const Vec128*b){ return a->w[0]==b->w[0] && a->w[1]==b->w[1]; }
static int eq256(const Vec256*a,const Vec256*b){ return a->w[0]==b->w[0] && a->w[1]==b->w[1] && a->w[2]==b->w[2] && a->w[3]==b->w[3]; }
static int zero256(const Vec256*v){ return !(v->w[0]|v->w[1]|v->w[2]|v->w[3]); }

static uint64_t mix64(uint64_t x){
  x^=x>>30; x*=UINT64_C(0xbf58476d1ce4e5b9);
  x^=x>>27; x*=UINT64_C(0x94d049bb133111eb);
  x^=x>>31; return x;
}

static void build_q(Mat128*q){
  memset(q,0,sizeof(*q));
  for(unsigned r=0;r<127;++r){
    q->row[r][r>>6] ^= UINT64_C(1)<<(r&63u);
    unsigned c=r+1u;
    q->row[r][c>>6] ^= UINT64_C(1)<<(c&63u);
  }
}

static void build_lifted_m(const Mat128*q,Mat256*m){
  memset(m,0,sizeof(*m));
  for(unsigned r=0;r<QWIDTH;++r){
    for(unsigned c=0;c<QWIDTH;++c){
      unsigned qb=(unsigned)((q->row[r][c>>6]>>(c&63u))&1u);
      if(qb){
        unsigned r0=2u*r, r1=r0+1u, c0=2u*c, c1=c0+1u;
        m->row[r0][c0>>6]^=UINT64_C(1)<<(c0&63u);
        m->row[r1][c1>>6]^=UINT64_C(1)<<(c1&63u);
      }
    }
  }
}

static void q_matvec(const Mat128*q,const Vec128*x,Vec128*y){
  memset(y,0,sizeof(*y));
  for(unsigned r=0;r<QWIDTH;++r){
    unsigned a=parity64(q->row[r][0]&x->w[0]) ^ parity64(q->row[r][1]&x->w[1]);
    if(a) set128(y,r);
  }
}

static void m_matvec(const Mat256*m,const Vec256*x,Vec256*y){
  memset(y,0,sizeof(*y));
  for(unsigned r=0;r<WIDTH;++r){
    unsigned a=0;
    for(unsigned w=0;w<WORDS;++w) a^=parity64(m->row[r][w]&x->w[w]);
    if(a) set256(y,r);
  }
}

static void lift(const Vec128*z,Vec256*x){
  memset(x,0,sizeof(*x));
  for(unsigned i=0;i<QWIDTH;++i) if(bit128(z,i)){ set256(x,2u*i); set256(x,2u*i+1u); }
}

static void project(const Vec256*x,Vec128*z){
  memset(z,0,sizeof(*z));
  for(unsigned i=0;i<QWIDTH;++i) if(bit256(x,2u*i)) set128(z,i);
}

static int invariant(const Vec256*x){
  for(unsigned i=0;i<QWIDTH;++i) if(bit256(x,2u*i)!=bit256(x,2u*i+1u)) return 0;
  return 1;
}

static void swap_pairs(const Vec256*x,Vec256*y){
  memset(y,0,sizeof(*y));
  for(unsigned i=0;i<QWIDTH;++i){
    if(bit256(x,2u*i)) set256(y,2u*i+1u);
    if(bit256(x,2u*i+1u)) set256(y,2u*i);
  }
}

static unsigned rank128(const Mat128*q){
  Vec128 rows[QWIDTH];
  for(unsigned r=0;r<QWIDTH;++r){ rows[r].w[0]=q->row[r][0]; rows[r].w[1]=q->row[r][1]; }
  unsigned rank=0;
  for(unsigned c=0;c<QWIDTH && rank<QWIDTH;++c){
    unsigned p=rank;
    while(p<QWIDTH && !bit128(&rows[p],c)) ++p;
    if(p==QWIDTH) continue;
    if(p!=rank){ Vec128 t=rows[p]; rows[p]=rows[rank]; rows[rank]=t; }
    for(unsigned r=0;r<QWIDTH;++r) if(r!=rank && bit128(&rows[r],c)){
      rows[r].w[0]^=rows[rank].w[0]; rows[r].w[1]^=rows[rank].w[1];
    }
    ++rank;
  }
  return rank;
}

int main(void){
  Mat128 Q; Mat256 M; build_q(&Q); build_lifted_m(&Q,&M);
  uint64_t commute_checks=0, bidi_checks=0;

  /* Exhaustive basis-level commutation test for the declared pair swap. */
  for(unsigned i=0;i<WIDTH;++i){
    Vec256 e={{0,0,0,0}}, pe, me, pme, mpe;
    set256(&e,i); swap_pairs(&e,&pe);
    m_matvec(&M,&e,&me); swap_pairs(&me,&pme);
    m_matvec(&M,&pe,&mpe);
    if(!eq256(&pme,&mpe)){
      fprintf(stderr,"rsa260_pair_orbit_quotient_bidi_256_oracle: FAIL commute basis=%u\n",i); return EXIT_FAILURE;
    }
    ++commute_checks;
  }

  /* Exhaustive quotient basis checks: project/lift and operator intertwining. */
  for(unsigned i=0;i<QWIDTH;++i){
    Vec128 z={{0,0}}, pz, qz; Vec256 x,mx,lq;
    set128(&z,i); lift(&z,&x); project(&x,&pz);
    if(!eq128(&z,&pz) || !invariant(&x)){
      fprintf(stderr,"rsa260_pair_orbit_quotient_bidi_256_oracle: FAIL bidi basis=%u\n",i); return EXIT_FAILURE;
    }
    q_matvec(&Q,&z,&qz); m_matvec(&M,&x,&mx); lift(&qz,&lq);
    if(!eq256(&mx,&lq)){
      fprintf(stderr,"rsa260_pair_orbit_quotient_bidi_256_oracle: FAIL intertwine basis=%u\n",i); return EXIT_FAILURE;
    }
    ++bidi_checks;
  }

  /* Broad deterministic invariant vectors. */
  for(uint64_t t=0;t<(UINT64_C(1)<<18);++t){
    Vec128 z={{mix64(t^UINT64_C(0x123456789abcdef0)),mix64(t^UINT64_C(0xfedcba9876543210))}}, pz,qz;
    Vec256 x,mx,lq;
    lift(&z,&x); project(&x,&pz);
    if(!eq128(&z,&pz) || !invariant(&x)){
      fprintf(stderr,"rsa260_pair_orbit_quotient_bidi_256_oracle: FAIL deterministic=%llu\n",(unsigned long long)t); return EXIT_FAILURE;
    }
    q_matvec(&Q,&z,&qz); m_matvec(&M,&x,&mx); lift(&qz,&lq);
    if(!eq256(&mx,&lq)){
      fprintf(stderr,"rsa260_pair_orbit_quotient_bidi_256_oracle: FAIL deterministic intertwine=%llu\n",(unsigned long long)t); return EXIT_FAILURE;
    }
    ++bidi_checks;
  }

  const unsigned qrank=rank128(&Q);
  Vec128 qkernel={{UINT64_MAX,UINT64_MAX}}, qzero;
  Vec256 kernel,mkernel; q_matvec(&Q,&qkernel,&qzero); lift(&qkernel,&kernel); m_matvec(&M,&kernel,&mkernel);
  if(qrank!=127 || qzero.w[0] || qzero.w[1] || zero256(&kernel) || !zero256(&mkernel)){
    fprintf(stderr,"rsa260_pair_orbit_quotient_bidi_256_oracle: FAIL kernel rank=%u\n",qrank); return EXIT_FAILURE;
  }

  Vec128 round; project(&kernel,&round);
  if(!eq128(&round,&qkernel)){
    fprintf(stderr,"rsa260_pair_orbit_quotient_bidi_256_oracle: FAIL kernel roundtrip\n"); return EXIT_FAILURE;
  }

  printf("rsa260_pair_orbit_quotient_bidi_256_oracle: ok; action=C2_pair_swap; orbits=128; full_width=256; quotient_width=128; q_rank=%u; q_nullity=%u; commute_basis=%llu; bidi_checks=%llu; lifted_kernel_weight=256; reduction_factor=2\n",
         qrank,QWIDTH-qrank,(unsigned long long)commute_checks,(unsigned long long)bidi_checks);
  return EXIT_SUCCESS;
}
