#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum { N=256, W=4, NF=7, MAXC=256, DRAWS=32 };
typedef struct { uint64_t row[N][W]; } Mat;
typedef struct { unsigned v[4]; uint32_t colour; } Class4;
typedef struct { uint32_t own; uint64_t out[NF], in[NF]; unsigned rd[NF], cd[NF], dg[NF]; } Sig;
static uint64_t rngs=UINT64_C(0x9e3779b97f4a7c15);
static uint64_t rng64(void){rngs^=rngs<<7;rngs^=rngs>>9;rngs^=rngs<<8;return rngs;}
static unsigned bit(const Mat*m,unsigned r,unsigned c){return (unsigned)((m->row[r][c>>6]>>(c&63u))&1u);} 
static void setb(Mat*m,unsigned r,unsigned c){m->row[r][c>>6]|=UINT64_C(1)<<(c&63u);} 
static void build(Mat*m, Mat f[3], Mat mark[3]){memset(m,0,sizeof(*m));memset(f,0,sizeof(Mat)*3);memset(mark,0,sizeof(Mat)*3);static const unsigned mate[3][4]={{1,0,3,2},{2,3,0,1},{3,2,1,0}};for(unsigned c=0;c<60;c++){unsigned b=4*c;for(unsigned i=0;i<4;i++)for(unsigned j=0;j<4;j++)if(i!=j)setb(m,b+i,b+j);if((c%20)+1<20)for(unsigned i=0;i<4;i++)setb(m,b+i,b+4+i);for(unsigned k=0;k<3;k++)for(unsigned i=0;i<4;i++)setb(&f[k],b+i,b+mate[k][i]);}for(unsigned comp=0;comp<3;comp++)for(unsigned i=comp*80;i<(comp+1)*80;i++)setb(&mark[comp],i,i);for(unsigned i=240;i+1<N;i++)setb(m,i,i+1);}
static uint64_t mix(uint64_t x){x^=x>>30;x*=UINT64_C(0xbf58476d1ce4e5b9);x^=x>>27;x*=UINT64_C(0x94d049bb133111eb);x^=x>>31;return x;}
static int cmpu(const void*a,const void*b){uint32_t x=*(const uint32_t*)a,y=*(const uint32_t*)b;return(x>y)-(x<y);} 
static uint64_t mh(uint32_t*a,unsigned n,uint64_t seed){qsort(a,n,sizeof(uint32_t),cmpu);uint64_t h=mix(seed^n);for(unsigned i=0;i<n;i++)h=mix(h^((uint64_t)a[i]+UINT64_C(0x9e3779b97f4a7c15)*(i+1)));return h;}
static int sigless(const Sig*a,const Sig*b){if(a->own!=b->own)return a->own<b->own;for(unsigned k=0;k<NF;k++){if(a->rd[k]!=b->rd[k])return a->rd[k]<b->rd[k];if(a->cd[k]!=b->cd[k])return a->cd[k]<b->cd[k];if(a->dg[k]!=b->dg[k])return a->dg[k]<b->dg[k];if(a->out[k]!=b->out[k])return a->out[k]<b->out[k];if(a->in[k]!=b->in[k])return a->in[k]<b->in[k];}return 0;}
static int sigeq(const Sig*a,const Sig*b){return !sigless(a,b)&&!sigless(b,a);} 
static void sortidx(unsigned idx[N],const Sig s[N]){for(unsigned i=0;i<N;i++)idx[i]=i;for(unsigned i=1;i<N;i++){unsigned x=idx[i],j=i;while(j&&sigless(&s[x],&s[idx[j-1]])){idx[j]=idx[j-1];j--;}idx[j]=x;}}
static unsigned refine(const Mat mats[NF],uint32_t col[N]){Sig s[N];unsigned idx[N];for(unsigned i=0;i<N;i++){memset(&s[i],0,sizeof(Sig));for(unsigned k=0;k<NF;k++){for(unsigned c=0;c<N;c++)s[i].rd[k]+=bit(&mats[k],i,c);for(unsigned r=0;r<N;r++)s[i].cd[k]+=bit(&mats[k],r,i);s[i].dg[k]=bit(&mats[k],i,i);}}sortidx(idx,s);uint32_t cc=0;col[idx[0]]=0;for(unsigned j=1;j<N;j++){if(!sigeq(&s[idx[j]],&s[idx[j-1]]))cc++;col[idx[j]]=cc;}for(unsigned it=0;it<64;it++){for(unsigned i=0;i<N;i++){s[i].own=col[i];for(unsigned k=0;k<NF;k++){uint32_t out[N],in[N];unsigned no=0,ni=0;s[i].rd[k]=s[i].cd[k]=s[i].dg[k]=0;for(unsigned c=0;c<N;c++)if(bit(&mats[k],i,c)){out[no++]=col[c];s[i].rd[k]++;}for(unsigned r=0;r<N;r++)if(bit(&mats[k],r,i)){in[ni++]=col[r];s[i].cd[k]++;}s[i].dg[k]=bit(&mats[k],i,i);s[i].out[k]=mh(out,no,17+2*k);s[i].in[k]=mh(in,ni,31+2*k);}}sortidx(idx,s);uint32_t nxt[N],nc=0;nxt[idx[0]]=0;for(unsigned j=1;j<N;j++){if(!sigeq(&s[idx[j]],&s[idx[j-1]]))nc++;nxt[idx[j]]=nc;}int same=1;for(unsigned i=0;i<N;i++)if(nxt[i]!=col[i])same=0;memcpy(col,nxt,sizeof(nxt));if(same)return nc+1;}return 0;}
static unsigned collect4(const uint32_t col[N],unsigned nc,Class4 c[MAXC]){unsigned cnt[N]={0};for(unsigned i=0;i<N;i++)cnt[col[i]]++;unsigned q=0;for(unsigned k=0;k<nc;k++)if(cnt[k]==4){c[q].colour=k;unsigned z=0;for(unsigned i=0;i<N;i++)if(col[i]==k)c[q].v[z++]=i;q++;}return q;}
static int preserve_class(const Mat mats[NF],const Class4*c,const unsigned p[4]){for(unsigned k=0;k<NF;k++)for(unsigned i=0;i<4;i++)for(unsigned j=0;j<4;j++)if(bit(&mats[k],c->v[i],c->v[j])!=bit(&mats[k],c->v[p[i]],c->v[p[j]]))return 0;return 1;}
static unsigned perms[24][4], nperm=0;
static void genperm(unsigned d,unsigned used,unsigned p[4]){if(d==4){memcpy(perms[nperm++],p,sizeof(unsigned)*4);return;}for(unsigned v=0;v<4;v++)if(!(used&(1u<<v))){p[d]=v;genperm(d+1,used|(1u<<v),p);}}
static void reqgraph(const Mat*m,const Class4*c,unsigned n,unsigned req[MAXC][MAXC]){memset(req,0,sizeof(unsigned)*MAXC*MAXC);for(unsigned a=0;a<n;a++)for(unsigned b=a+1;b<n;b++){int hit=0;for(unsigned i=0;i<4&&!hit;i++)for(unsigned j=0;j<4&&!hit;j++)if(bit(m,c[a].v[i],c[b].v[j])||bit(m,c[b].v[j],c[a].v[i]))hit=1;if(hit)req[a][b]=req[b][a]=1;}}
static unsigned components(const unsigned req[MAXC][MAXC],unsigned n,unsigned co[MAXC]){for(unsigned i=0;i<n;i++)co[i]=MAXC;unsigned nc=0;for(unsigned s=0;s<n;s++)if(co[s]==MAXC){unsigned q[MAXC],h=0,t=0;q[t++]=s;co[s]=nc;while(h<t){unsigned u=q[h++];for(unsigned v=0;v<n;v++)if(req[u][v]&&co[v]==MAXC){co[v]=nc;q[t++]=v;}}nc++;}return nc;}
static unsigned map_comp(unsigned x,const Class4*c,unsigned n,const unsigned co[MAXC],unsigned comp,const unsigned p[4]){for(unsigned a=0;a<n;a++)if(co[a]==comp)for(unsigned i=0;i<4;i++)if(x==c[a].v[i])return c[a].v[p[i]];return x;}
static int commute_comp(const Mat*m,const Class4*c,unsigned n,const unsigned co[MAXC],unsigned comp,const unsigned p[4]){for(unsigned r=0;r<N;r++){unsigned pr=map_comp(r,c,n,co,comp,p);for(unsigned q=0;q<N;q++){unsigned pq=map_comp(q,c,n,co,comp,p);if(bit(m,pr,pq)!=bit(m,r,q))return 0;}}return 1;}
static unsigned orbit_removed_for_permset(const unsigned ok[24]){unsigned parent[4]={0,1,2,3};for(unsigned k=0;k<24;k++)if(ok[k])for(unsigned i=0;i<4;i++){unsigned a=i,b=perms[k][i];while(parent[a]!=a)a=parent[a];while(parent[b]!=b)b=parent[b];if(a!=b)parent[b]=a;}unsigned roots=0;for(unsigned i=0;i<4;i++){unsigned a=i;while(parent[a]!=a)a=parent[a];int first=1;for(unsigned j=0;j<i;j++){unsigned b=j;while(parent[b]!=b)b=parent[b];if(a==b){first=0;break;}}roots+=first;}return 4-roots;}
static unsigned infer_score(const Mat*m,const Mat f[3],const Mat mark[3]){Mat mats[NF];mats[0]=*m;for(unsigned k=0;k<3;k++)mats[1+k]=f[k];for(unsigned k=0;k<3;k++)mats[4+k]=mark[k];uint32_t col[N];unsigned nc=refine(mats,col);Class4 cls[MAXC];unsigned n=collect4(col,nc,cls);if(!n)return 0;unsigned req[MAXC][MAXC],co[MAXC];reqgraph(m,cls,n,req);unsigned comps=components(req,n,co);unsigned total=0;for(unsigned comp=0;comp<comps;comp++){unsigned localok[24];for(unsigned k=0;k<24;k++){localok[k]=1;for(unsigned a=0;a<n;a++)if(co[a]==comp&&!preserve_class(mats,&cls[a],perms[k])){localok[k]=0;break;}if(localok[k]&&!commute_comp(m,cls,n,co,comp,perms[k]))localok[k]=0;}unsigned removed=orbit_removed_for_permset(localok),classes=0;for(unsigned a=0;a<n;a++)if(co[a]==comp)classes++;total+=removed*classes;}return total;}
static int switch2x2(Mat*m,unsigned r1,unsigned c1,unsigned r2,unsigned c2){if(r1==r2||c1==c2)return 0;unsigned a=bit(m,r1,c1),b=bit(m,r1,c2),c=bit(m,r2,c1),d=bit(m,r2,c2);if(a==d&&b==c&&a!=b){m->row[r1][c1>>6]^=UINT64_C(1)<<(c1&63);m->row[r1][c2>>6]^=UINT64_C(1)<<(c2&63);m->row[r2][c1>>6]^=UINT64_C(1)<<(c1&63);m->row[r2][c2>>6]^=UINT64_C(1)<<(c2&63);return 1;}return 0;}
static void scramble(const Mat*src,Mat*dst,unsigned steps){*dst=*src;for(unsigned t=0;t<steps;t++)switch2x2(dst,rng64()%N,rng64()%N,rng64()%N,rng64()%N);}
int main(void){unsigned p[4];genperm(0,0,p);Mat M,F[3],C[3];build(&M,F,C);unsigned observed=infer_score(&M,F,C);printf("observed_removed=%u quotient=%u\n",observed,N-observed);if(observed!=180)return 2;unsigned ge=0,min=999,max=0,sum=0;for(unsigned d=0;d<DRAWS;d++){Mat nul;scramble(&M,&nul,20000);unsigned s=infer_score(&nul,F,C);if(s>=observed)ge++;if(s<min)min=s;if(s>max)max=s;sum+=s;printf("draw=%u removed=%u quotient=%u\n",d,s,N-s);}printf("draws=%u null_min=%u null_max=%u null_sum=%u ge=%u empirical_p=%u/%u\n",DRAWS,min,max,sum,ge,1+ge,1+DRAWS);return 0;}
